### ISSUE TITLE
proxy error when rsession startup is slow

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/nbrsessionproxy#2]
If the user has some content loaded in their rsession and it doesn't fully start up before the browser connects to it, the user will see a proxy error.

Refreshing the window will connect to the working session.

We need to wait until the session is available before switching to it.

**Comment by yuvipanda** [comment]
We do this now right?

**Comment by ryanlovett** [comment]
Yep, fixed by your exponential backoff patch.
