### ISSUE TITLE
Support jupyterlab 0.30

### ISSUE THREAD

**Issue by eyadsibai** [jupyterhub/nbrsessionproxy#23]
Unfortunately, did not manage to install this package since it doesn't support the latest jupyterlab version.

**Comment by tkinz27** [comment]
https://github.com/Viasat/nbrsessionproxy is our fork, and we are keeping it somewhat up to date. Jupyterlab is still and beta so everytime they update jupyterlab we need to update every single package to support it. We are currently running version 0.29.2 and I'm not sure when we will get it updated for 0.30 or the recently released 0.31

**Comment by data301** [comment]
I would strongly recommend the recently released 0.31 series of JupyterLab, which is the first official beta release.

**Comment by yuvipanda** [comment]
@tkinz27 would love a PR!

**Comment by tkinz27** [comment]
I actually do not work at Viasat so I do not have an environment for working with it. I may get some time to look into it again but there are guys at Viasat who are actively working on it. @DerekHeldtWerle not sure if you have updated things in a while.

**Comment by ryanlovett** [comment]
nbrsessionproxy supports 0.35 now, https://github.com/jupyterhub/nbrsessionproxy/commit/cb7cc3daa3404c1a1210969444ffc18904cf658f
