### ISSUE TITLE
Configuration variable precedence

### ISSUE THREAD

**Issue by ianabc** [jupyterhub/nbrsessionproxy#6]
Where should configuration changes for the RSessionContext configurables `path`, `cmd` and `env` go? I tried `c.RSessionContext.env` in jupyter_notebook_config.py but that seemed to be ignored.

**Comment by ryanlovett** [comment]
Yes, sorry. That is how I intended config to function, but since this extension isn't a NotebookApp it doesn't read the config file. If I merge #7 then all of this goes away. Otherwise I'll probably use the tornado settings mechanism to read the config. I'll make a choice shortly.

**Comment by ianabc** [comment]
Hi Ryan perfect, thank you. I'm working with @cmd-ntrf on some of the same systems and we're using his modifications now and it is indeed working for us. I think the only configurable he has left is [RSessionContext.cmd](https://github.com/jupyterhub/nbrsessionproxy/pull/7/files). Feel free to close this if you want.

**Comment by ryanlovett** [comment]
The config is now auto-detected directly from R which is what rserver does.
